server:
  port: 9091

spring:
  application:
    name: backend-gateway-client

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
      default-filters:
        - TokenRelay
      routes:
        - id: actuator-health
          uri: http://backend-gateway-client:9091
          predicates:
            - Path=/api/health
          filters:
            - StripPrefix=0

        - id: actuator-info
          uri: http://backend-gateway-client:9091
          predicates:
            - Path=/api/info
          filters:
            - StripPrefix=1

        - id: auth-service-register
          uri: http://auth-service:8081
          predicates:
            - Path=/api/register
          filters:
            - RemoveRequestHeader=Authorization
            - StripPrefix=0

        - id: auth-service-login
          uri: http://auth-service:8081
          predicates:
            - Path=/api/login
          filters:
            - RemoveRequestHeader=Authorization
            - StripPrefix=0

        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            - TokenRelay

        - id: backend-resources
          uri: http://backend-resources:9191
          predicates:
            - Path=/api/resources/**
          filters:
            - StripPrefix=0
            - TokenRelay

        - id: audit-service
          uri: http://audit-service:8082
          predicates:
            - Path=/api/audit/**
          filters:
            - StripPrefix=0
            - TokenRelay

        - id: wallet-service
          uri: http://wallet-service:8083
          predicates:
            - Path=/api/wallets/**
          filters:
            - StripPrefix=0
            - TokenRelay

        - id: transaction-service
          uri: http://transaction-service:8084
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=0
            - TokenRelay

        - id: notification-service
          uri: http://notification-service:8085
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
            - TokenRelay

        - id: template-login
          uri: http://template-service:8086
          predicates:
            - Path=/template/login,/favicon.ico
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie

        - id: template-register
          uri: http://template-service:8086
          predicates:
            - Path=/template/register,/favicon.ico
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie

        - id: template-service
          uri: http://template-service:8086
          predicates:
            - Path=/template/home,/favicon.ico
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie

        - id: template-static
          uri: http://template-service:8086
          predicates:
            - Path=/assets/**,/assets/css/**,/assets/js/**,/assets/images/**,/assets/webfonts/**
          filters:
            - StripPrefix=0

#        - id: template-service
#          uri: http://template-service:8086
#          predicates:
#            - Path=/templates/**
#          filters:
#            - StripPrefix=1


  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://backend-keycloak-auth:8080/realms/ArmeniaBank
        registration:
          backend-gateway-client:
            client-id: backend-gateway-client
            client-secret: gateway-service
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
            provider: keycloak

      resourceserver:
        jwt:
          issuer-uri: http://backend-keycloak-auth:8080/realms/ArmeniaBank

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,beans

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG