server:
  port: 8086

spring:
  application:
    name: template-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://backend-keycloak-auth:8080/realms/ArmeniaBank

gateway:
  base-url: http://localhost:9091

auth-service:
  url: http://auth-service:8081
